### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GuillaumePressiat** [GuillaumePressiat/nasql#1]
- [x] Onglet avec les parcours de patients (sunburst ou tramineR) par type d'autorisation T2A
- [x] Valorisation des rsa ?
- [x] Solution pour un export solide des données en xls (ou xlsx), json et csv
- [x] Ajout des listes de codes diagnostics / actes des manuels de GHM pour les requêtes ?
- [x] Améliorer la saisie de requêtes manuelles
- [x] consolider l'export de listes en json
- [x] import de listes en json ?
- [ ] origine géo des patients comme [kharto](https://github.com/deepPhong/kharto) mais directement sur les rsa requêtés ? avec les codes géographiques PMSI
- [ ] écrire et consolider la connexion possible à une bdd locale  
- [x] explorer les listes de requêtes sous forme de table, la ccam et la CIM ?
- [x] Améliorer affichage des datatable (nowrap)
